const CustomerPrivacyPolicy = () => {
    return (
        <div className="mt-20 lg:px-[67px] w-full px-[20px] sm:px-[50px]">
            <div className="lg:w-[60%]">
                <h1 className=" text-[24px] lg:text-[2.25rem] text-[#111111] font-semibold mb-10">Ayatrio Customer Privacy Policy</h1>
                <div className="flex flex-col">
                    <h2 className="font-semibold text-[14px] mb-[8px]">A partnership in trust.</h2>
                    <p className="text-[14px] mb-[12px] text-[#484848]">We will make sure that your personal information is protected when it is sent outside of the Ayatrio Group. We make sure our trusted service partners keep your personal information safe. When Ayatrio set out to create a high-quality, low-priced line of home furnishings, we knew we couldn't do it without the help of some very important partners-you, our customers. Whether you're researching purchases in the Ayatrio catalogue, picking up your furniture in our self-serve warehouses or assembling your purchases at home-we're working together to help you create a better everyday life at a price everyone can afford. Ayatrio is based on a partnership with our customers. Without you, Ayatrio could not exist. This partnership extends to the way we handle your personal information. Just like shopping at Ayatrio is a cooperative experience, Ayatrio makes a point of working with our customers when it comes to their privacy. We only collect the information we may need to create a better shopping experience for you. This Privacy Notice is our way of telling you what information we collect, how we use it and how you can access, change and remove your information. </p>
                </div>
                <div className="flex flex-col">
                    <h2 className="font-semibold text-[14px] mb-[8px] mt-[32px]">Help us build a better Ayatrio.</h2>
                    <p className="text-[14px] mb-[12px] text-[#484848]">To create a better Ayatrio, we need your help. You can help by providing us with various kinds of information to help Ayatrio serve you better, and ultimately improve Ayatrio for everyone. Below you’ll find some of the reasons we request information from you, as well as how we obtain and use that information to help improve your Ayatrio shopping experience. </p>
                    <p className="text-[14px] mb-[12px] text-[#484848]">Purchases – When you make a purchase at Ayatrio, you may need to give us your credit card number or contact information to process your payment. If the item is being delivered, we will also ask for your name, address, telephone number and email address to guarantee prompt delivery. This information will only be used for internal purposes and to fulfil your purchase. </p>
                    <p className="text-[14px] mb-[12px] text-[#484848]">Customer Service – In order for a customer service representative to respond to your questions or concerns, we may need personal information like your name, address, email, and telephone number. This information is only used to answer your questions as completely and thoroughly as possible. </p>
                    <p className="text-[14px] mb-[12px] text-[#484848]">Special offers, promotions and guarantees – When you register for or redeem Ayatrio special offers or other promotions, we may ask for personal information to note the success of our programs for future offers. You also may provide such information when you fill out a guaranteed card about a product you purchased from Ayatrio. Or you may provide us with information such as product preferences, reasons for purchasing a product, or family and lifestyle information to help us learn more about your shopping preferences.</p>
                    <p className="text-[14px] mb-[12px] text-[#484848]">CCTV Footage: We use CCTV in our stores for the purposes of safety, security, and monitoring. We only store the information collected by CCTV for a period which allows us to assist regulatory bodies and law enforcement agencies. This information is kept in secure environments and access is restricted to deputed security personnel only.</p>
                    <p className="text-[14px] mb-[12px] text-[#484848]">Feedback Form: When you shop with us in our stores, after billing you might interact with our partners asking you to fill a form to provide your feedback on shopping experience. Form might ask for some personal data which is collected to gain insights of our customers and to improvise our services. This is voluntary and not compulsive. </p>
                    <p className="text-[14px] mb-[12px] text-[#484848]">Delivery Services: When you shop with us and request for home delivery of the products, we collect your personal data like your name, full address with zip code, email id and phone number. This information is also shared with our TSPs (Transport Service Provider) for them to able to deliver your order to your location. We have agreements with them to keep your data secure and is used only for the purpose to provide the defined service. Post the purchase of the product and delivery service, Ayatrio or TSP do not ask you for any extra delivery charge. Please stay cautious of online frauds. When in doubt please reach out to our Customer Support Center. </p>
                    <p className="text-[14px] mb-[12px] text-[#484848]">Assembly Services: When you directly opt for assembly services through our partners, data provided by you to the partners stays with them and Ayatrio do not get any access to it. Please read Terms and Conditions of all the services before opting, to better understand the usage of your personal data.</p>
                    <p className="text-[14px] mb-[12px] text-[#484848]">Shopping with Ayatrio: Shop only at Ayatrio stores or visit our Ayatrio India website www.Ayatrio.in or use Ayatrio App. Ayatrio India does not sell on any other websites/channels/platforms. Beware of fake websites/accounts claiming to sell Ayatrio products. Ayatrio will not be responsible or accountable for any such purchases and/or for any data loss that may happen on any other websites/channels/platforms. When in doubt please reach out to our customer support center.</p>
                </div>
                <div className="flex flex-col">
                    <h2 className="font-semibold text-[14px] mb-[8px] mt-[32px]">What you share with Ayatrio stays with Ayatrio.</h2>
                    <p className="text-[14px] mb-[12px] text-[#484848]">We take the security of your personal data very seriously. We have implemented various strategies, controls, policies, and measures to keep your data secure and keep these measures under close review. We do our best to ensure that your data is protected and only accessible to Ingka Group employees (or subcontractors) who need it to carry out their job responsibilities. We are committed to providing appropriate security controls to protect your personal information.</p>
                    <p className="text-[14px] mb-[12px] text-[#484848]">If you would like to obtain a copy of your personal data with us, or if you would like to ask us to correct or delete your personal data or to exercise other individual rights, you can contact Ayatrio Customer Support and they will help you out. However, the requests will be processed considering legal and regulatory requirements.</p>
                </div>
                <div className="flex flex-col">
                    <h2 className="font-semibold text-[14px] mb-[8px] mt-[32px]">Ayatrio Family Members:</h2>
                    <p className="text-[14px] mb-[12px] text-[#484848]">When you as an Ayatrio Family member interact with us in our stores, the personal data will be collected such as name, date of birth, e-mail address and home address, purchasing activity, such as product preferences, information about your family such number of children, type of family (Joint, Nuclear) and other interactions you may have with us. The purpose of collecting this data is to perform statistical analysis to get insights on customer purchase, trends and engagements. This data will be stored and retained with us till you continue to use our services and / or as necessary to comply with legal obligations.</p>
                    <p className="text-[14px] mb-[12px] text-[#484848]">If you are logged in to any Ayatrio Channel like Ayatrio Web or Ayatrio App, we collect your data (only if you identify as an Ayatrio Family member) to better understand how you use these different channels and how they play together.</p>
                </div>
                <div className="flex flex-col">
                    <h2 className="font-semibold text-[14px] mb-[8px] mt-[32px]">Ayatrio Business Network Members.</h2>
                    <p className="text-[14px] mb-[12px] text-[#484848]">It is completely voluntary to sign up as a user of the Business Network Account. However, if you do, we need to know who you are so that we can administrate and secure the Account, enable the functionalities connected to the Account and communicate with you in various matters related thereto. For these purposes we will collect your name, company name, email address, and telephone number (optional) and number of the Ayatrio for Business Card that we issue for you. We will also collect and store information about the purchases that you have made on behalf of your company as well as your other activities on the Account. The information about the purchase history and user activity may be used to send tailored direct marketing if you have specifically consented to receiving such communication. </p>
                    <p className="text-[14px] mb-[12px] text-[#484848]">The administrator of the Account (which is a person within your company) will be able to see the purchases that you have made on behalf of the company and registered on the Account. The Account is operated by Ayatrio IT AB (which is another company in Ingka Group) and its trusted internal as well as third party service providers. We will keep your personal data if you are a registered user of the Account. All personal data will be deleted when the Account is terminated.</p>
                </div>
                <div className="flex flex-col">
                    <h2 className="font-semibold text-[14px] mb-[8px] mt-[32px]">There are many kinds of cookies. We think you'll like the Ayatrio recipe.</h2>
                    <p className="text-[14px] mb-[12px] text-[#484848]">The Ayatrio web site uses cookies to remember your preferences. For example, the web site may remember which Ayatrio store page you view, to make your next visit more convenient (by displaying information more relevant to that store location). Nevertheless, if you don't like having any cookies at all they can be disabled in your web browser's Internet Options.</p>
                </div>
                <div className="flex flex-col">
                    <h2 className="font-semibold text-[14px] mb-[8px] mt-[32px]">Out of sight, but never out of reach.</h2>
                    <p className="text-[14px] mb-[12px] text-[#484848]">If you are unhappy with the way, we process your personal data please let us know and we will do our best to address your concern. Call us at 1800 419 4532 or click HERE. We will respond to your questions or concerns as quickly as possible. By using this site, you consent to the above privacy policy. </p>
                </div>
            </div>
        </div>
    );
}

export default CustomerPrivacyPolicy;